---
# Install PostgreSQL on Enterprise Linux 6 (RHEL/CentOS/Scientific)
- hosts: database_servers
  user: ansible
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/main.yml'
  vars:
    el_version: 6
    postgresql_version: 9.4
  tasks:
    - include: 'tasks/main.yml'
